# fly.toml app configuration file generated for nomadpal-backend on 2025-08-16T17:02:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nomadpal-backend'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
